### ISSUE TITLE
ERROR: Service 'app' failed to build

### ISSUE THREAD

**Issue by flik** [dannym87/php-kafka#2]
Here is detail: 

`
ERROR: Service 'app' failed to build: The command '/bin/sh -c apt-get update     && apt-get install -y librdkafka-dev git zip unzip wget     && pecl install rdkafka     && docker-php-ext-enable rdkafka     && wget https://raw.githubusercontent.com/composer/getcomposer.org/863c57de1807c99d984f7b56f0ea56ebd7e5045b/web/installer -O - -q | php -- --quiet --install-dir=/usr/local/bin --filename=composer     && chmod +x /usr/local/bin/composer' returned a non-zero code: 1

`

**Comment by flik** [comment]
Here is the solution update the docker file:

`
FROM php:7.1

RUN apt-get update \\
    && apt-get install -y librdkafka-dev git zip unzip wget
RUN pecl install rdkafka \\
    && docker-php-ext-enable rdkafka
    # composer
RUN curl -s https://getcomposer.org/installer | php \\
&& mv composer.phar /usr/local/bin/composer

`

**Comment by dannym87** [comment]
Sorry about that - Thanks for the fix https://github.com/dannym87/php-kafka/commit/f9e4ff5c5650854424118b23c06f4a406579e4b7
